# Generated by Django 6.0.2 on 2026-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
