# Generated by Django 6.0.2 on 2026-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_perfume_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
